name: Build and Publish Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: |
          python -m build --wheel

      - name: Show build artifacts
        run: |
          ls -lh dist/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
