name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the wheel
        run: |
          python -m build --wheel

      - name: Create GitHub Release and upload wheel
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl